### ISSUE TITLE
integrate request scope dataloader

### ISSUE THREAD

**Issue by tbo-axelor** [graphql-java-kickstart/graphql-java-servlet#105]
how to integrate request scope data loader in  graphql-java-servlet version 6.1.3 ??

**Comment by oliemansm** [comment]
Can you provide some more detail at which point you're stuck or you're getting an error? You mentioned on Gitter that the information in the readme didn't help, but your question is very generic atm. So do you have a specific problem or is the info in the readme not enough to get started and you need a working example?

**Comment by tbo-axelor** [comment]
yes i need working example

**Comment by oliemansm** [comment]
@ashu-walmart Do you have a working example lying around by any chance that you could share? Because I'm not sure when I would have the time to figure this out and provide a working example

**Comment by tbo-axelor** [comment]
ok it's fine...i have no working example...i am creating simple graphql-java example like creating schema then implement datafethcer to fetch data from database.
but now i want to implement request scope dataloader.but no idea how to done

**Comment by oliemansm** [comment]
Much appreciated, thanks!

**Comment by ashu-walmart** [comment]
Here you go. https://github.com/ashu-walmart/request-scoped-dataloader. @oliemansm, this example probably belongs to spring boot starter vs this graphql-java-servlet repository. I am happy to open a PR if you feel it is useful there.

**Comment by oliemansm** [comment]
@tbo-axelor So take a look at the example @ashu-walmart created: https://github.com/ashu-walmart/request-scoped-dataloader.
