### ISSUE TITLE
A way to limit number of queries in batched request

### ISSUE THREAD

**Issue by tbatie** [graphql-java-kickstart/graphql-java-servlet#107]
I've been looking at how to prevent malicious requests. I saw that graphql-java implemented query complexity validation, but it appears each query is validated individually through the servlet. Is there a way to validate the overall complexity of the batched request? Or limit the number of queries within the batched request? If there is currently no way, what would be the best approach to solving this? I'd be happy to put up a PR. Thanks!

**Comment by oliemansm** [comment]
Hi @tbatie. Have you send this request to the guys from `graphql-java` as well? This question seems to be more related to that separate project, than this one.

**Comment by tbatie** [comment]
@oliemansm yeah, I agree. I'll ask around over there. Thanks!
