### ISSUE TITLE
overriding GraphQLContext in 6.1.x

### ISSUE THREAD

**Issue by MarkNenadov** [graphql-java-kickstart/graphql-java-servlet#108]
I'm upgrading an old version of graphql-java-servlet up to 6.1.3. 

In the existing code, I extended SimpleGraphQLServlet, overwrote createContext() to make it to return a wrapper which added an addCookie() method so I could add a cookie from my resolver via dataFetchingEnvironment.getContext().addCookie(). 

This all broken with the upgrade, and I'm not seeing any clarity as to whether I can do this in 6.1.x. I now see the new way to build the servlet (GraphQLServletListener, etc.), but I'm not seeing an equivalent of createContext(). I do see the GraphQLContextBuilder and I think I understand how I can use it to create the customized context, but it's not clear to me how I can connect the result of GraphQLContextBuilder.build () to a GraphQLServletListener so I can fetch it from the data fetching environment in my resolver. Can anyone show me what I'm missing or point me in the right direction? Thanks.

**Comment by oliemansm** [comment]
@MarkNenadov 
The documentation needs to be updated as you've clearly noticed. Does the following snippet help you?

```java
List<GraphQLServletListener> listeners;
GraphQLSchema graphqlSchema;
GraphQLContextBuilder contextBuilder;

GraphQLInvocationInputFactory = invocationInputFactory = GraphQLInvocationInputFactory.newBuilder(graphqlSchema)
  .withGraphQLContextBuilder(contextBuilder)
  .build();
SimpleGraphQLHttpServlet graphqlServlet = SimpleGraphQLHttpServlet.newBuilder(invocationInputFactory)
  .withListeners(listeners)
  .build();
```
We just release version 6.1.4 btw and the `groupId` has been changed to `com.graphql-java-kickstart`.

**Comment by MarkNenadov** [comment]
@oliemansm , Thanks a lot for this example which shows how the context builder and servlet connect. Also thanks a lot for the hint about the groupId changing, I was wondering where 6.1.4 was in the other group.

That said, looking more closely at the GraphQLContextBuilder and GraphQLContext, it appears that HttpServletResponse has been removed.  So unless there is some other way around it, I still have no way to add the cookie from the resolver, because I've now lost my ability to use the context as a way to set the response cookie. The old servlet class's createContext() method provided access to the HttpServletResponse--which is how I could wrap the context to set the cookie.

**Comment by oliemansm** [comment]
@MarkNenadov I see that has been inadvertently removed during a recent refactoring. I'll reinstate it in the next release.
