### ISSUE TITLE
Custom error message for http 400

### ISSUE THREAD

**Issue by gingerdin** [graphql-java-kickstart/graphql-java-servlet#129]
Hi,

I need to return the custom error message with concrete structure (general structure for the whole application) for the HTTP 400. In case, for example, when the user provided totally wrong request
(e.g. <app_url>/graphql)

Seems that there is no possibility to provide extensions to the graphql.servlet.AbstractGraphQLHttpServlet#AbstractGraphQLHttpServlet(java.util.List<graphql.servlet.GraphQLServletListener>, boolean) for the getHandler

Thanks for any help

**Comment by oliemansm** [comment]
@gingerdin We're about to refactor that part so will keep this in mind while doing so.

**Comment by kito99** [comment]
As things currently stand, I don't see how the `onError()` callback would ever be called for post requests, since handler defined in `AbstractGraphQLHttpServlet` always catches exception and sets the response code to 500:

```
        this.postHandler = (request, response) -> {
            GraphQLInvocationInputFactory invocationInputFactory = configuration.getInvocationInputFactory();
            GraphQLObjectMapper graphQLObjectMapper = configuration.getObjectMapper();
            GraphQLQueryInvoker queryInvoker = configuration.getQueryInvoker();

            try {
...
            } catch (Exception e) {
                log.info("Bad POST request: parsing failed", e);
                response.setStatus(STATUS_BAD_REQUEST);
            }
        };
```

When the handler is called, it'll never reach `onError()`; it actually calls `onSuccess()` instead:

```
    private void doRequest(HttpServletRequest request, HttpServletResponse response, HttpRequestHandler handler, AsyncContext asyncContext) {

        List<GraphQLServletListener.RequestCallback> requestCallbacks = runListeners(l -> l.onRequest(request, response));

        try {
            handler.handle(request, response);
            runCallbacks(requestCallbacks, c -> c.onSuccess(request, response));
        } catch (Throwable t) {
            response.setStatus(500);
            log.error("Error executing GraphQL request!", t);
            runCallbacks(requestCallbacks, c -> c.onError(request, response, t));
        } finally {
            runCallbacks(requestCallbacks, c -> c.onFinally(request, response));
            if (asyncContext != null) {
                asyncContext.complete();
            }
        }
    }
```
