### ISSUE TITLE
how to provide custom GraphQLContext in 7.0.0 ？

### ISSUE THREAD

**Issue by dave3068** [graphql-java-kickstart/graphql-java-servlet#131]
I want to get some authorization user information in the QueryResolver.

the article [https://www.howtographql.com/graphql-java/5-authentication/] said, I can custom GraphQLContext to do this.

But in the version 7.0.0 SimpleGraphQLHttpServlet has maked as deprecated, and GraphQLHttpServlet with GraphQLConfiguration can't tack the CustomGraphQLContext in.

How can I do this?

**Comment by oliemansm** [comment]
Thanks for reporting. Will be fixed in the next version so you can pass the `GraphQLContextBuilder` into the `GraphQLConfiguration`

**Comment by oliemansm** [comment]
New release fixing this is syncing to central now. Will take a couple of hours probably before it's available.
