### ISSUE TITLE
Way to override DefaultGraphQLErrorHandler

### ISSUE THREAD

**Issue by maierson** [graphql-java-kickstart/graphql-java-servlet#132]
Hello,

Thank you for the project.
I've just migrated from 4.0 to 7.1.1 and I'm getting very generic error messages: 

`internal Server Error(s) while executing query`

This makes very hard to debug things particularly in dev mode.
Is there a way to override `DefaultGraphQLErrorHandler` with a `CustomGraphQLErrorHandler`?

Thank you
Dahn

**Comment by oliemansm** [comment]
Are you using `graphql-spring-boot` together with this by any chance? Because the latest version of that includes an option to override this default error handler with one that actually returns the actual exception that occurred.

Otherwise you could add your own error handler like this:

```java
GraphQLObjectMapper objectMapper = GraphQLObjectMapper.newBuilder()
    .withGraphQLErrorHandler(new CustomGraphQLErrorHandler())
    .build();
GraphQLConfiguration configuration = GraphQLConfiguration.with(schema)
    .with(objectMapper)
    .build();
GraphQLHttpServlet servlet = GraphQLHttpServlet.with(configuration);
```

**Comment by maierson** [comment]
No Spring boot but the override works perfectly. Thank you. 👍
