### ISSUE TITLE
Is @defer already supported?

### ISSUE THREAD

**Issue by ahhhkah** [graphql-java-kickstart/graphql-java-servlet#133]
Hi,

is the @defer-Directive already supported by the servlet? (https://www.graphql-java.com/documentation/v11/defer/)
Any plans on implementing it in the near future?

Thank you in advance,
ahhhkah

**Comment by oliemansm** [comment]
@ahhhkah This project simply wraps `graphql-java`, so would expect most if not all to just work. Have you tried it?

**Comment by ahhhkah** [comment]
Yes, we tried a requests with @defer on our API, but the "deferredResults" in the extensions was empty. I think the AbstractGraphQLHttpServlet.java has to be changed quite a bit to support it.

If we find the time, we will create a pull request. If you start working on it (or have an idea what has to be done), let us know.

**Comment by oliemansm** [comment]
Ok, haven't looked at that defer stuff yet. Please note that there's a branch splitting up this project in two modules, so if you want to start work on this make sure to base it on that one. Seeing you mention it needs quite some changes it would otherwise become a nightmare to merge.
