### ISSUE TITLE
Returning graphql enum values to the client

### ISSUE THREAD

**Issue by valasatava** [graphql-java-kickstart/graphql-java-servlet#140]
Hi! I'm new to GraphQL and will appreciate any comments on my issue. We use the graphql-spqr library to convert our POJOs into a GraphQL schema that is then passed to the servlet (from graphql-java-servlet library). For Enums we face a following issue (just a pet example):
```javascript
public enum MyTypeEnum {
    _1_VALUE("first value"),
    _2_VALUE("second value");
}
```

I'd like the client get in JSON payload:
```javascript
{
  "data": {
    "my_type": "first value"
  }
}
```

but what currently goes through is:
```javascript
{
  "data": {
    "my_type": "_1_VALUE"
  }
}
```

GraphQL schema won't tolerate an arbitrary string as Enum name. So I was wandering if there is a way to inject a customization at serialization step so that given a GraphQLEnumType in the schema, we can return a corresponding value of Enum value and not name?

Thank you in advance!

**Comment by oliemansm** [comment]
@valasatava First thing that comes to mind is to try to use directives to customize the way you want to serialize enums. There's an example how to use directives for fields in the docs that you could tweak to get it to work for enums: https://www.graphql-java-kickstart.com/tools/directives/.
