### ISSUE TITLE
GraphQL subscriptions without graphql-java-tools - How?

### ISSUE THREAD

**Issue by michael-fl** [graphql-java-kickstart/graphql-java-servlet#148]
[stacktrace.txt](https://github.com/graphql-java-kickstart/graphql-java-servlet/files/2885851/stacktrace.txt)
Hello,

I try to setup a Spring Boot based GraphQL service (based on project `graphql-spring-boot-starter`), which does *not* use `graphql-java-tools`, but builds the RuntimeWiring manually/programmatically. GraphQL queries and mutations work just fine that way. However, I have problems to make subscriptions work.

I've added the following wiring to bind the DataFetcher for the subscription:

```java
        RuntimeWiring.Builder runtimeWiringBuilder =
            newRuntimeWiring()
            ...
                .type(TypeRuntimeWiring.newTypeWiring("Subscription")
                    .dataFetcher("stockQuotes", gqlService::stockQuotes)
                );
```

And my resolver function returns correctly an `org.reactivestream.Publisher`

```java
    Publisher<StockPriceUpdate> stockQuotes(DataFetchingEnvironment env) {
        return stockTickerPublisher.getPublisher();
    }
```

However, if I call my subscription from GraphiQL or GraphQL Playground, I get the following error:
"No serializer found for class graphql.execution.reactive.CompletionStageMappingPublisher" (stack trace attached).

It looks like that `GraphQLObjectMapper` from lib `graphql-java-servlet` tries to serialize the result, which is a (wrapped) `org.reactivestream.Publisher`, directly as a JSON result. That does not make sense, of course. Instead it should subscribe as listener to the publisher and push updates via the WebSocket whenever the Publisher emits the next update.

As far as I understood, `graphql-java-servlet` already has built-in support for subscriptions via WebSockets. Unfortunately there is no plain-vanilla example available, which does subscriptions without using graphql-tools.

Any ideas how I can get this working? Thanks a lot!

Best, Michael

PS: The relevant parts of my `application.yml` file are those:

```yaml
server:
  port: 9200

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    websocket:
      enabled: true
      path: /graphql
    subscriptions:
      websocket:
        path: /graphql
```

**Comment by oliemansm** [comment]
I've only used it in combination with `graphql-java-tools` myself. Have you taken a look at the example of subscriptions in `graphql-java` which is used by `graphql-java-servlet`? Perhaps that helps in finding a solution? See: https://www.graphql-java.com/documentation/v11/subscriptions/.

**Comment by michael-fl** [comment]
Solved. Solution: Do not use the Electron based version of GraphiQL (GraphiQL.app). It seems to be no longer in active development. When using the web based version of GraphiQL it works just fine.
Closing this issue.
