### ISSUE TITLE
Allow customization of batched request handling

### ISSUE THREAD

**Issue by jmccaull** [graphql-java-kickstart/graphql-java-servlet#151]
We need some way to customize how batch queries are being handled. The initial ask was to limit the number of request within each batch, but then I realized what happens when this limit is met should likewise be customizable. 
This is my initial work up of a solution: https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/149
We would also like to see the option to process the requests in parallel and I am considering making that section of logic injectable as well, with the current behavior being default. 
I noticed there was an ask back in October relating to validation across requests in a batch, but as this has nothing to do with validating individual requests(and unless I'm missing something) it felt appropriate here.
Thoughts, concerns, suggestions?
Thanks

**Comment by jmccaull** [comment]
I moved a little more out of the query invoker and into the ExecutionResultHandler - much happier with how this works. I plan on writing a second specification to test this on its own

**Comment by ashu-walmart** [comment]
@oliemansm what are your thoughts on this?

**Comment by oliemansm** [comment]
Thanks @jmccaull for this, I've merged the PR. There's a `return null` in the `DefaultGraphQLServlet` that raised an eyebrow, but that's not the only thing in this project that needs refactoring.

**Comment by ashu-walmart** [comment]
Thanks @oliemansm.

**Comment by jmccaull** [comment]
Thanks @oliemansm, and yeah I thought about that and figured it would be better to be consistent with the existing pattern and let it all be refactored together at once. Any chance you can do a release for this please? I'm planning to do a pr to the spring boot project based on this work, thanks!

**Comment by oliemansm** [comment]
@jmccaull Version 7.3.0 is syncing to maven central now.
