### ISSUE TITLE
Cannot get generated schema with /schema.json

### ISSUE THREAD

**Issue by kc7bfi** [graphql-java-kickstart/graphql-java-servlet#152]
I have implemented a GraphQLHttpServlet in my application that is running within Wildfly. My servlet endpoint is https://ip/GraphQPService/graphql. When I try to retrieve the schema from, https://ip/GraphQPService/graphql/schema.json I get a 404 Not Found. However, I am able to execute my graphql queries using an HTTP POST. Any idea what I might be doing wrong? David

**Comment by kc7bfi** [comment]
The problem turned out to be an error in defining my servlet. In the example given at https://www.graphql-java-kickstart.com/servlet/getting-started/#create-a-servlet-class, the servlet URL patter is shown as:

urlPatterns = {"graphql"}

however, it needed to be:

urlPatterns = {"graphql/*"}

**Comment by oliemansm** [comment]
Thanks for pointing it out, I'll update the docs.
