### ISSUE TITLE
Setting up GraphQLWebsocketServlet when using GraphQLServlet (outside of Spring Boot)

### ISSUE THREAD

**Issue by crumhorn** [graphql-java-kickstart/graphql-java-servlet#157]
Our main "GraphQL servlet" extends GraphQLHttpServlet and I annotate it with @WebServlet() for it to be loaded by our application server. As we are in a Wildfly environment we don't want to use Spring Boot as they don't really make sense to be used together (we only use it for the GraphiQL interface during development). 

Until now this has worked fine. However, I want to use GraphQL Subscriptions, and I can't for the life of me figure out how our extension of GraphQLHttpServlet can interact with the GraphQLWebsocketServlet class.

How do I go about setting up the GraphQLWebsocketServlet from a standard GraphQLHttpServlet instance? I see the class has constructors, but it's clear it's not really intended to be extended as the constructor wants too much in the parameters, so adding another @WebServlet() and @Endpoint() doesn't seem to be the way to do it. They also use the same configured factories, so it seems they should be shared.

I looked through the source code on how Spring auto wires it based on the .yml config files, but I still can't see how they relate to each other or interact with each other.

Thanks in advance!

**Comment by oliemansm** [comment]
I think it has been written with usage by `graphql-spring-boot` in mind. To use it in its current form with another platform would indeed require you to extend it and pass in all those parameters. If you create your `GraphQLHttpServlet` with a `Configuration` you could reuse that existing `Configuration` in your own `GraphQLWebsocketServlet` to pass in the same objects.

The class can definitely be improved though.

**Comment by mbell-gresham** [comment]
I'm essentially trying to do the same thing, and use GraphQL Servlet to run our GraphQL Services (we can't use spring either). Is there a working example of it anywhere?

@crumhorn did you ever get it to work?

**Comment by crumhorn** [comment]
@mbell-gresham No, never did, for now I create a normal websocket listener and send my events in raw json, which gets us what we need, but not what we want... quite frustrating.

**Comment by wlfbck** [comment]
I guess nothing new on this front? Honestly i'm in despair right now trying to figure out how to make subscriptions work without using spring boot.

@oliemansm I think this may be something which should be stated in the README.md, i spend quite a while trying to figure out why i can't get this to work (doesn't help that i'm new to web development).

**Comment by vojtapol** [comment]
@wlfbck Nothing is planned for this yet. We would be happy to accept a PR if you want to look into it.

**Comment by aznguy** [comment]
Yes, I'm very well interested in this subject as well. How to setup a `GraphQLWebsocketServlet`. Some sample code on how to instantiate would be great. Preferable in plain Java without the use of Spring of course.

**Comment by lorenzleutgeb** [comment]
I found [this solution](https://github.com/MuhammadAdeelUsman/kafka-connect/tree/975072691eff3315e521e80eedfc959adb553bfb/graphql/aggregator/src/main/java/io/debezium/examples/graphql/endpoint) which certainly is not optimal, but better than what @crumhorn described.

**Comment by oliemansm** [comment]
I've added a sample with Embedded Jetty here: [servlet sample](https://github.com/graphql-java-kickstart/samples/tree/master/servlet-hello-world).
