### ISSUE TITLE
How to deploy GraphQL Servlet to Karaf?

### ISSUE THREAD

**Issue by jeujai** [graphql-java-kickstart/graphql-java-servlet#165]
I can build the OSGi examples into a Karaf distribution but http://localhost:8181/graphql/schema.json doesn't resolve. There are no errors in the Karaf log. It doesn't look like the GraphQL Servlet has been deploy. Do I need to create a servlet class and deploy it to Karaf as a web archive first? If so, how do I do that? Sorry about these basic questions? I'm a Karaf newbie.

**Comment by sergehuber** [comment]
Actually this work but a new PR has been created to update the dependencies of the example project : https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/166

**Comment by oliemansm** [comment]
Fixed by #166
