### ISSUE TITLE
how to implement CORS in GraphQLHttpServlet

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [graphql-java-kickstart/graphql-java-servlet#172]
`

@WebServlet(name = "GraphQLEndpoint", urlPatterns = {"graphql/*"}, loadOnStartup = 1)
public class GraphQLEndpoint extends GraphQLHttpServlet implements GraphQLServletListener {

    @Override
    protected GraphQLConfiguration getConfiguration() {
        return GraphQLConfiguration.with(createSchema()).build();
    }

    private GraphQLSchema createSchema() {
        String schema = "type Query{hello: String}";

        SchemaParser schemaParser = new SchemaParser();
        TypeDefinitionRegistry typeDefinitionRegistry = schemaParser.parse(schema);

        RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
                .type(TypeRuntimeWiring.newTypeWiring("Query")
                                .dataFetcher("hello", new StaticDataFetcher("world"))
                )
                .build();

        SchemaGenerator schemaGenerator = new SchemaGenerator();
        return schemaGenerator.makeExecutableSchema(typeDefinitionRegistry, runtimeWiring);
    }

}
`

This works fine in Graphql_playground but doesn't work when consumed from front-end application hosted in different domain or port number.  I am not using Spring-boot but a simple webapp generated from maven.

**Comment by oliemansm** [comment]
When googling this I found this article which seems to provide all the info you need to enable CORS in your use case: https://www.logicbig.com/tutorials/java-ee-tutorial/java-servlet/servlet-cors.html.
