### ISSUE TITLE
Stop sending empty extension map

### ISSUE THREAD

**Issue by jmccaull** [graphql-java-kickstart/graphql-java-servlet#174]
After switching over to the java graphql provided tracing backed metrics we started getting an empty extensions map in our responses. This is because the metrics utilizes the tracing extension to generate the data, then removes the extension causing the map to no longer be null.
I've tried handling this with Jackson settings(WRITE_EMPTY_JSON_ARRAYS), but I think the way the object mapper is set up prevents this from working. I initially worked up a pr to handle this within the metrics in the spring boot project, but that requires using a java graphql internal api.
I think this ends up being the cleanest, and easiest place to handle it. Thoughts @oliemansm ? 
https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/173

**Comment by oliemansm** [comment]
Looks like the cleanest solution, merged it.

**Comment by jmccaull** [comment]
thanks!
