### ISSUE TITLE
OSGiServlet not working in an enRoute Setup

### ISSUE THREAD

**Issue by Sandared** [graphql-java-kickstart/graphql-java-servlet#181]
Hi,

I tried to setup a minimal example on how to use your GraphQL Servlet in a pure enRoute OSGi setup. First I tried to merely include your library and then copy&paste the example code of your Karaf example in my own component. 

Unfortunately this didn't work, as the [`OsgiGraphQLHttpServlet`](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/OsgiGraphQLHttpServlet.java) wasn't registered via the HttpWhiteboard. 

I think this might stem from the component properties of `OsgiGraphQLHttpServlet` that are incorrect according to the [standard](https://osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html#service.http.whiteboard-i21223311). Instead of using `alias=/graphql` you should use either the new annotations like this `@HttpWhiteboardServletPattern("/graphql")` or use the old style property like this `osgi.http.whiteboard.servlet.pattern=/graphql`

I've created a small runnable example that you can inspect via [Gitpod](https://gitpod.io) if you want: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#https://github.com/jatoms-io/io.jatoms.osgi.graphql/blob/master/graphql/impl/src/main/java/io/jatoms/graphql/MyGraphQLServlet.java)

Just cd in to /graphql , type `resolve app` and when maven is finished `run app/target/debug.jar` 

Maybe you could change the properties accordingly so that the `OsgiGraphQLHttpServlet` is usable in a plain OSGi environment too.

Kind regards,
Thomas

**Comment by sergehuber** [comment]
I think this was a problem with support for older OSGi platforms. I wonder if we can put both properties at the same time ?

**Comment by Sandared** [comment]
Also for older OSGi platforms the new approach should work, if they are compliant to the standard. I think this property might rather be to satisfy a proprietary framework. However, I think there is no problem in adding both properties.

**Comment by oliemansm** [comment]
I don't have any OSGi experience myself unfortunately. Is one of you able to create a PR for this one?

**Comment by oliemansm** [comment]
@benfortuna You seem to have OSGi experience. Any chance you could help out with this one?

**Comment by benfortuna** [comment]
@oliemansm I don't have a specific fix for supporting the HttpWhiteboard service, but perhaps the change applied in #237 (servlet is not automatically registered) could help in that users can register their own servlet using HttpWhiteboard.

**Comment by Sandared** [comment]
AFAIK the changes in the mentioned PR indeed fix the issue by using standard OSGi annotations instead of the outdated ones from biz.aQute 😊

**Comment by oliemansm** [comment]
This should be fixed with the recently release 9.1.0 version as mentioned above.
