### ISSUE TITLE
Apollo like file uploads

### ISSUE THREAD

**Issue by jmccaull** [graphql-java-kickstart/graphql-java-servlet#193]
Currently, for resolvers to handle multipart requests the parts are obtained through the GraphQLServletContext. This dependency is a little odd because the parts have to be processed in both the AbstractServlet and in the context.
It would be nice to remove this dependency from the context. Ideally it would look similar to the way Apollo handles files: https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675.
I think this would mean that the file object would become available within the data fetching environment for the resolver specified in the map part of the Apollo request spec, though I could see some explicitly defined type (as Apollo handles it) getting replaced with the file object. The ladder of the two may be too difficult, but I could see the former being implemented by two methods: modifying the schema obtained by the GraphQLSchemaProvider to add the file as an argument for the data fetcher(or similar),  or even a custom instrumentation to add the file into the environment.

**Comment by oliemansm** [comment]
This is already supported in combination with graphql-spring-boot-starter. There's a sample here: https://github.com/graphql-java-kickstart/samples/tree/master/file-upload.
