### ISSUE TITLE
Why not the open and close event of GraphQLWebsocketServlet be triggered when using the graphql subscription  and establishing or closing a websocket? 

### ISSUE THREAD

**Issue by weipinglee** [graphql-java-kickstart/graphql-java-servlet#195]
I want to listen the event of establishing or closing a websocket from the client ,why not the open and close event of GraphQLWebsocketServlet be triggered,isn't this automatically triggered?

**Comment by oliemansm** [comment]
I don't understand the question. How are you trying to listen to these events?

**Comment by oliemansm** [comment]
Closed due to inactivity.
