### ISSUE TITLE
Is it possible to make ApolloSubscriptionProtocolHandler more pluggable

### ISSUE THREAD

**Issue by verunder** [graphql-java-kickstart/graphql-java-servlet#197]
This is clearly enhancement/extension request. 

**Here is the situation description**:
Basically, we use different server instead of spring-boot library. Vert.X to be specific. 
While ApolloSubscriptionProtocolHandler class is awesome and has all the functionality that I need,  it is based off different classes that I have the handle to with Vert.X. (Vert.x web-socket does not implement javax.websocket.Session). 

I was wondering if you are open to the possibility of refactoring the ApolloSubscriptionProtocolHandler into something that is more pluggable and does not depend on the javax.websocket.Session(at minimum)? I can help, if necessary. 

Sorry if I stepped over the line with this request. :)

**Comment by oliemansm** [comment]
Definitely open to that. Not sure when I'll be able to work on that, so contributions are welcome too!

**Comment by oliemansm** [comment]
This will be released in 9.0.0, see #217.
