### ISSUE TITLE
Question: AbstractGraphQLHttpServlet init() called on get and post requests 

### ISSUE THREAD

**Issue by pstarritt-evooq** [graphql-java-kickstart/graphql-java-servlet#212]
Hello,

I was reading over the library and was curious to know why init() is called on every get/post request? 
As each thread will share the getHandler & posthandler instances, so we are overriding the shared instances between request interleaving?

postHandler = {AbstractGraphQLHttpServlet$lambda@12811} 
getHandler = {AbstractGraphQLHttpServlet$lambda@12812} 

Thanks ! 

Change from this Commit:
https://github.com/graphql-java-kickstart/graphql-java-servlet/commit/d440d7e40c82566cb6755cd5e52ef7c77d72d31c

**Comment by oliemansm** [comment]
Thanks, this is fixed in #217
