### ISSUE TITLE
GraphQLWebsocketServlet.modifyHandshake(): how do you call it?

### ISSUE THREAD

**Issue by ilitarist** [graphql-java-kickstart/graphql-java-servlet#214]
I'm trying to run Subscriptions using graphql.servlet.GraphQLWebsocketServlet. As far as I can see Websocket Endpoint modifyHanshake method is supposed to be called from configurator the way it's described here: https://javaee.github.io/tutorial/websocket010.html Configurator is a separate object from Endpoint, but graphql.servlet.GraphQLWebsocketServlet has methods of both Endpoint and Configurator. 

I ended up using my own configurator that puts request data into user properties. I've rewrote 
GraphQLWebsocketServlet sources so that important stuff from modifyHandshake (putting subscriptionProtocolFactory into user properties) is done in onOpen(). I can't just override onOpen() cause I need to call private methods like getSubscriptionProtocolFactory() so it's all very messy. Clearly it's not an intended solution. What am I missing here? Isn't it a common practice to have a separate configurator?

**Comment by oliemansm** [comment]
Have you looked at how it's done in the spring boot starter? It's using Spring specific classes, but might give you some ideas about how to do it for your use case? See https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/ccc2307ba7fe16335a4c89ba3c2e26752b2a0125/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWsServerEndpointRegistration.java.

**Comment by ilitarist** [comment]
I see now. I thought GraphQLWebsocketServlet itself is supposed to be used as the main configuration class. This makes sense now.
