### ISSUE TITLE
Omission in https://github.com/graphql-java-kickstart/graphql-java-servlet/README.md

### ISSUE THREAD

**Issue by MarkNenadov** [graphql-java-kickstart/graphql-java-servlet#216]
In https://github.com/graphql-java-kickstart/graphql-java-servlet/README.md, the code sample for "Context and DataLoader settings" has an element that doesn't make sense. It refers to this.batchLoaders, but that isn't defined or inhereited anywhere in the class.

**Comment by oliemansm** [comment]
@MarkNenadov Thanks, I've updated the documentation and moved it to the [documentation site](https://www.graphql-java-kickstart.com/servlet/dataloaders/).
