### ISSUE TITLE
OperationCallback is not present on GraphQLServletListener as Documentation said

### ISSUE THREAD

**Issue by DanielFaria** [graphql-java-kickstart/graphql-java-servlet#225]
Hello Everyone.

Documentation said that is possible capture error thought GraphQLServletListener implementing
the method 'GraphQLServletListener.OperationCallback onOperation(GraphQLContext context, String operationName, String query, Map<String, Object> variables) ''

However, this method is no longer present on GraphQLServletListener class.

Is there another way to capture error at Graphql Operation and catch its parameters?

Thanks.

**Comment by tomasAlabes** [comment]
Related to https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/96

**Comment by oliemansm** [comment]
Removal of the `OperationCallback` was before my time, so not entirely sure but it looks like it has been removed in favor of `Instrumentation` already provided by graphql-java directly. I've updated the README and the [documentation](https://www.graphql-java-kickstart.com/servlet/servlet-listener/#instrumentation).

If you have any more in depth questions about custom `Instrumentation` implementation please raise the issue at [graphql-java](https://github.com/graphql-java/graphql-java).
