### ISSUE TITLE
Cannot run example code

### ISSUE THREAD

**Issue by janacm** [graphql-java-kickstart/graphql-java-servlet#228]
I get the following error:

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.
> 
> The injection point has the following annotations:
> 	- @org.springframework.beans.factory.annotation.Autowired(required=true)
> 
> 
> Action:
> 
> Consider defining a bean of type 'graphql.GraphQL' in your configuration.
> 
> 
> Process finished with exit code 1
> 
> 

When trying to run the example project. Any idea why?

**Comment by oliemansm** [comment]
You mean [this example](https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/example) in the graphql-spring-boot-starter project? I just ran that one successfully today even. Could you pull in the latest changes and try again?

**Comment by oliemansm** [comment]
Closed due to inactivity and not being able to reproduce.

**Comment by leer5** [comment]
I received exactly this same error but I'm not running the sample project code.  I have a schema file which I used to generate the boiler plate code and I wrote code to do a query.  What does the error message actually mean?
