### ISSUE TITLE
graphql.servlet package not being exported in OSGI environment

### ISSUE THREAD

**Issue by aznguy** [graphql-java-kickstart/graphql-java-servlet#232]
Recently I've migrated from release 8.0.0 to 9.0.1 due to some bugs that have been fixed in that release. (https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/196)
There are some changes made in the organization of the project. Which is fine but I encountered some problems. 

What I've discovered is that the _graphql.servlet_ package has been movedfrom _Export-Package_ to _Private-package_. I was wondering is was done intentionally. 

Version 9.0.1 META-INF/MANIFEST.MF:
`
Private-Package: graphql.servlet,graphql.servlet.apollo,graphql.servle
 t.config,graphql.servlet.context,graphql.servlet.core,graphql.servlet
 .core.internal,graphql.servlet.input,graphql.servlet.osgi,graphql.ser
 vlet.subscriptions
...
`
VS

Version 8.0.0 META-INF/MANIFEST.MF:
`Export-Package: graphql.servlet;version="8.0.0";uses:="graphql.executi
 on.preparsed,graphql.schema,graphql.servlet.config,graphql.servlet.co
 ntext,graphql.servlet.core,graphql.servlet.input,javax.servlet,javax.
 servlet
....`

Because of this I'm getting the error that _osgi.wiring.package=graphqlservlet_  cannot be found. during the build of my OSGI Environment.

Please let me know if more information is needed or how to tackle this problem.

Best regards,
Aznguy

**Comment by oliemansm** [comment]
I'm not familiar with OSGI tbh, and also haven't changed that myself. Can you see how that was changed? Are you able to create a PR for it to fix it?

**Comment by benfortuna** [comment]
I've just added a PR that should fix this: #236

**Comment by aznguy** [comment]
Ah cool Thanks @benfortuna!,

I also managed to get it working locally. But unfortunately I´m behind cooperate firewall which restricts me from pushing to remote.
