### ISSUE TITLE
Can we change the name of ObjectMapperConfigurer?

### ISSUE THREAD

**Issue by bsara** [graphql-java-kickstart/graphql-java-servlet#234]
With the reorganization of code in the `graph-java-...` projects. There are now two `ObjectMapperConfigurer` classes. One in this project and one in `graphql-java-tools`. It seems like it would be prudent to rename them each to be specific to their respective projects...that, or share the code somehow between them. I just got bit by the fact that I thought I was using the correct `ObjectMapperConfigurer` because I thought that there was only one...only to finally discover, after a few hours of debugging, that there are actually two classes with the same name.

Perhaps we could name them `GraphQLServletObjectMapperConfigurer` and `GraphQLSchemaParserObjectMapperConfigurer`?

**Comment by oliemansm** [comment]
Yeah, that would indeed be better, good point.

**Comment by oliemansm** [comment]
Included in 9.1.0
