### ISSUE TITLE
Next Release of graphql-java-servlet

### ISSUE THREAD

**Issue by rwilliams-r7** [graphql-java-kickstart/graphql-java-servlet#239]
Was just hoping for an eta on the next graphql-java-servlet release. We are hitting a large defect and looking for the fix below.

https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/219

Just wondering when the next release will be out?

**Comment by oliemansm** [comment]
That particular bug was fixed and released in 9.0.1. Are you still on 9.0.0 (or lower)?

**Comment by rwilliams-r7** [comment]
@oliemansm My apologise I did not check maven or the commits I just looked at the releases tab on github and only seen 9.0.0. I will build now thank you.
