### ISSUE TITLE
graphql.kickstart.execution package missed in source.jar and javadoc.jar

### ISSUE THREAD

**Issue by ihrachou** [graphql-java-kickstart/graphql-java-servlet#257]
At the moment there are 2 root folders with source code: **graphql-java-kickstart** and **graphql-java-servlet**. It happens that only **graphql-java-servlet** is used to create sources and javadoc artifacts that are published to Maven Central. E.g. there is no sources and javadoc for *graphql.kickstart.execution.error.DefaultGraphQLErrorHandler*.

It would be great if sources and javadoc are consistent with binaries.

**Comment by oliemansm** [comment]
@ihrachou Checked the configuration and maven central, but it is in fact part of the packages. As far as I know that's a requirement from Maven Central and think it's not even possible to push without it. If you click the button "Downloads" at the top right you'll see you can download the sources.jar and javadoc.jar files, so they're really there: https://search.maven.org/artifact/com.graphql-java-kickstart/graphql-java-kickstart/10.0.0/jar.
