### ISSUE TITLE
graphql.GraphQL bean required

### ISSUE THREAD

**Issue by leer5** [graphql-java-kickstart/graphql-java-servlet#271]
In my project, I have a schema and I used the maven plugin to generate code to query a GraphQL server. This is client side code.    Even without writing any additional code to use the generated code, when I run the program, I get the following. My code sends results of the query to a soap endpoint and I have hard coded values for now pending new code to query the GraphQL server.

So the steps to reproduce for me are:  1 use plugin to generate code 2 package the code 3 run program

Description:

Field graphQL in graphql.spring.web.servlet.components.DefaultGraphQLInvocation required a bean of type 'graphql.GraphQL' that could not be found.

The injection point has the following annotations:

@org.springframework.beans.factory.annotation.Autowired(required=true)
Action:

Consider defining a bean of type 'graphql.GraphQL' in your configuration.

Process finished with exit code 0

**Comment by oliemansm** [comment]
I don't follow what you're really trying to do here and what's happening. There's some kind of SOAP endpoint involved and some kind of GraphQL client apparently and some generated code... You're best of opening an issue on Stackoverflow instead. This issue board is intended for feature requests or actual bugs.

**Comment by leer5** [comment]
Sure, thank you for rely.

Robert
