### ISSUE TITLE
Graphql-Java 16.0 support

### ISSUE THREAD

**Issue by Larkhis** [graphql-java-kickstart/graphql-java-servlet#280]
Hello, 
A new version of graphql-java was released yesterday [v16.0](https://github.com/graphql-java/graphql-java/releases/tag/v16.0), so it will be cool to profit from latest improvements.
Thanks

**Comment by timward60** [comment]
I opened the same feature request in [graphql-java-tools](https://github.com/graphql-java-kickstart/graphql-java-tools), looks like there are some breaking changes that will require a bit of work. See [graphql-java-tools:Issue#457](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/457)
