### ISSUE TITLE
GraphQLPostInvocationInputParser may distort query string read from HttpServletRequest

### ISSUE THREAD

**Issue by jdlib** [graphql-java-kickstart/graphql-java-servlet#385]
```GraphQLPostInvocationInputParser``` uses ```request.getReader().lines().collect(joining())``` to read the query string from the request. This effectively removes all line breaks from the request body.
But the query might have used these line breaks as token separator, therefore the resulting query may become invalid.

Example: Given a request body of 
```
{ 
hero {
name
weight
} }
```
this will result in a query string ```{hero {nameweight}}``` and fail since there is no such attribute.

I would suggest to use ```request.getReader().lines().collect(joining(" "))``` to read the request body, therefore replacing line breaks with a space.

**Comment by oliemansm** [comment]
Good catch. Apparently nobody ever encountered this since most people apply proper indentation in the GraphQL queries which causes nobody to actually run into this bug in reality. I've added a fix as proposed.
