### ISSUE TITLE
Cannot error handle on creating `GraphqlInvocationInput`

### ISSUE THREAD

**Issue by heowc** [graphql-java-kickstart/graphql-java-servlet#417]
**Describe the bug**

Hello. Thank you for creating such a wonderful library.

Our service is using this library, but we encountered a problem during the version upgrade. (11.0.0 -> 12.0.0)

The problem we experienced is that when creating a `GraphqlInvocationInput`, an error occurs and it cannot be handled. For example, we are using an option related to the file size limit, which causes a `FileSizeLimitExceededException` . It used to be able to handle this, but it seems to be missing as this changes in 11.0.1.

The problematic content is that the commit reflected in 11.0.1 is https://github.com/graphql-java-kickstart/graphql-java-servlet/commit/f8fbadbb4221167aa71a5ff1f985483838d6da1b.

**To Reproduce**
1. `MultipartConfigElement` custom settings
      - set `maxFileSize` small
2. Large file request beyond `maxFileSize`

**Expected behavior**

We should be able to handle errors like before 11.0.1.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by heowc** [comment]
See https://github.com/heowc/graphql-java-servlet/pull/1

**Comment by sgrannan** [comment]
You seem to be having the same issues as me when upgrading and I just commented on the original issue that resulted in the error handling removal breaking change #293 

Need an answer how to resolve this from @oliemansm
