### ISSUE TITLE
support for newer servlet specs

### ISSUE THREAD

**Issue by eduarddrenth** [graphql-java-kickstart/graphql-java-servlet#484]
In the meantime jakarta ee 10 is out, containing servet 6.0.

Please consider support for newer jakarta servlet specs so we can phase out the old.

The migration should be fairly straightforward, renaming javax to jakarta.

You can for example provide `<classifier>jakarta</classifier>` in pom.xml.

**Comment by oliemansm** [comment]
That would make it incompatible with current Spring Boot version I believe. With Spring Boot 3.0 this should be doable.

**Comment by eduarddrenth** [comment]
ok, I don't use any spring or spring-boot, but instead jakarta ee / cdi. Perhaps I should look for another solution that follows ee stack instead of spring stack?

**Comment by oliemansm** [comment]
We can release a major update of this library and simply not update this dependency in the spring related projects. That way it could already be used. Any contributions to implement this would be appreciated.

**Comment by eduarddrenth** [comment]
I'll see if I can do a PR for this
