### ISSUE TITLE
OperationCallback no longer exists

### ISSUE THREAD

**Issue by apkrasny** [graphql-java-kickstart/graphql-java-servlet#96]
The README points out that GraphQLServletListener has both RequestCallback and OperationCallback. OperationCallback seems to have been removed and I am having trouble finding a replacement for it. Specifically I was using it to track metrics (operation count, operation time, etc). Is there an alternative that should be used?

https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServletListener.java

**Comment by kclaes** [comment]
I solved this by implementing my own Instrumentation.
Essentially I was also using it for metrics, so I ended up subclassing TracingInstrumentation. Only instead of adding it to the response, i collected the necessary information and sent it to my metrics service instead.

**Comment by apkrasny** [comment]
Thanks @kclaes for the idea of subclassing TracingInstrumentation, worked great. Completely satisfied my use case. For anyone else you just need to override instrumentExecutionResult and the parameters have the operation name while the instrumentation state has duration, startTime, endTime, etc.

**Comment by subeeshcbabu** [comment]
Any idea why `OperationCallback` got removed? This was really useful to get access to all the Errors  - `List<GraphQLError> errors` via the `onError` callback. Any replacement for this API?

For instrumenting the metrics, using `TracingInstrumentation` makes sense, and I am going to find examples for that. However, wondering if that supports instrumenting error scenarios as well?

**Comment by oliemansm** [comment]
@subeeshcbabu Please see [this comment](https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/225#issuecomment-629613464).
