### ISSUE TITLE
How to show dataloader statistics in graphql response

### ISSUE THREAD

**Issue by marshi** [graphql-java-kickstart/graphql-java-servlet#98]
i want to show dataloader statistics in GraphQL response like below.
```
"extensions": {
    "dataloader": {
      "overall-statistics": {
        "loadCount": 8,
        "loadErrorCount": 0,
        ....
      },
      "individual-statistics": {
        "replies": {
          "loadCount": 8,
          "loadErrorCount": 0,
          "loadErrorRatio": 0,
          ....
        }
      }
```

In order to show the statistics, DataLoaderDispatcherInstrumentationOptions is needed to be set to DataLoaderDispatcherInstrumentation constructor.
However, in the graphql-java-servlet library, DataLoaderDispatcherInstrumentationOptions isn't set to the constructor.
https://github.com/graphql-java/graphql-java-servlet/blob/e94d00e749dcc20a2ae474bb39072f3080800f06/src/main/java/graphql/servlet/GraphQLQueryInvoker.java#L68

I've tried to extend GraphQLQueryInvoker and override ExtendedGraphQLInvoker#getInstrumentation method.
```
override fun getInstrumentation(context: Any?): Instrumentation {
    return if (context is GraphQLContext) {
      context.dataLoaderRegistry
          .map { registry ->
            val instrumentations = ArrayList<Instrumentation>()
            instrumentations.add(getInstrumentation.get())
            // 👇 add DataLoaderDispatcherInstrumentationOptions.newOptions().includeStatistics(true)
            instrumentations.add(DataLoaderDispatcherInstrumentation(registry, DataLoaderDispatcherInstrumentationOptions.newOptions().includeStatistics(true)))
            ChainedInstrumentation(instrumentations)
          }
          .map { it as Instrumentation }
          .orElse(getInstrumentation.get())
    } else getInstrumentation.get()
  }
```
I've be able to show dataloader statistics, but I don't want to take this approach.

Is there any way to set DataLoaderDispatcherInstrumentationOptions to the constructor, or to show dataloader statistics?

**Comment by oliemansm** [comment]
Just quickly scanned the current solution and your question. Looks like it would be better if the construction of the `DataLoaderDispatcherInstrumentation` would be refactored away into some kind of `Factory` class that you could set during construction. If no custom factory is provided it would use the current approach in a default factory.

So it would look something like this:
```java
return ((GraphQLContext) context).getDataLoaderRegistry()
  .map(registry -> {
    List<Instrumentation> instrumentations = new ArrayList<>();
    instrumentations.add(getInstrumentation.get());
    instrumentations.add(dataLoaderInstrumentationFactory.create(registry));
    return new ChainedInstrumentation(instrumentations);
  })
  .map(Instrumentation.class::cast)
  .orElse(getInstrumentation.get());
```
Where that factory in your case could do:
```java
public class FactoryWithStatistics implements DataLoaderInstrumentationFactory {
  public Instrumentation create(DataLoaderRegistry registry) {
    return new DataLoaderDispatcherInstrumentation(registry, DataLoaderDispatcherInstrumentationOptions.newOptions().includeStatistics(true));
  }
}
```
An alternative would be some kind of provider class where any settings to use when constructing new instrumentations could be set. Maybe that one's a bit simpler actually.
